import os
from dotenv import load_dotenv

#Load Dotenv
load_dotenv()

#Import the env variables
PG_DB_URI=os.getenv('PG_DATABASE_URI')
PG_SERVER_HOST=os.getenv('PG_SERVER_HOST')
PG_USER_PASSWORD=os.getenv('PG_USER_PASSWORD')
PG_DBNAME=os.getenv('PG_DBNAME')
PG_USER=os.getenv('PG_USER')
AZURE_STORAGE_ACCESS_KEY = os.getenv('BLOB_ACCESS_KEY')
AZURE_STORAGE_CONNECTION_STRING = os.getenv('BLOB_CONNECTION_STRING')

MLFLOW_SERVER_URI=os.getenv('MLFLOW_SERVER_URI')
AZURE_SUBSCRIPTION_ID=os.getenv('AZURE_SUBSCRIPTION_ID')
AZURE_RESOURCE_GROUP=os.getenv('AZURE_RESOURCE_GROUP')
AZURE_TENANT_ID=os.getenv('AZURE_TENANT_ID')
AZURE_SRV_PRINCIPAL_PASSWORD=os.getenv('AZURE_SRV_PRINCIPAL_PASSWORD')
AZURE_SRV_PRINCIPAL_ID=os.getenv('AZURE_SRV_PRINCIPAL_ID')
AZURE_SRV_PRINCIPAL_NAME=os.getenv('AZURE_SRV_PRINCIPAL_NAME')